version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0
    parallelism: 1
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      # - run: npm run test
      - run: yarn prettier:check
      - run: yarn build
